FROM nginx
# Note that the default conf file for Nginx is located at: /etc/nginx/conf.d/default.conf within the container
COPY default.conf /etc/nginx/conf.d/default.conf
COPY build /usr/share/nginx/html