apiVersion: v1
kind: Pod                                            
metadata:
  name: car-sharing-auth-demo-client
  labels:
    app: car-sharing-auth-demo-client                                 
spec:                                                
  containers:
    - image: harveyyifanli/car-sharing-auth-demo-client-v8
      name: car-sharing-auth-demo-client                         
      ports:
        - containerPort: 80                          