apiVersion: v1
kind: Service              
metadata:
  name: car-sharing-auth-demo-client-lb
spec:
  type: LoadBalancer       
  ports:
  - port: 80               
    protocol: TCP          
    targetPort: 80         
  selector:                
    app: car-sharing-auth-demo-client      